
.PHONY : all
all: go-build

.PHONY : install
install: go-install

.PHONY : clean
clean: go-clean

.PHONY : go-build
go-build:
	go build -v ./...

.PHONY : go-install
go-install:
	go install -v ./...

.PHONY : go-clean
go-clean:
	go clean -v ./...